const countries = [
  { name: 'Afghanistan', iso: 'AF', countryCode: 93, priority: 0 },
  { name: 'Albania', iso: 'AL', countryCode: 355, priority: 0 },
  { name: 'Algeria', iso: 'DZ', countryCode: 213, priority: 0 },
  { name: 'American Samoa', iso: 'AS', countryCode: 1, priority: 0 },
  { name: 'Andorra', iso: 'AD', countryCode: 376, priority: 0 },
  { name: 'Angola', iso: 'AO', countryCode: 244, priority: 0 },
  { name: 'Anguilla', iso: 'AI', countryCode: 1, priority: 6 },
  { name: 'Antarctica', iso: 'AQ', countryCode: 672, priority: 0 },
  { name: 'Antigua and Barbuda', iso: 'AG', countryCode: 1, priority: 0 },
  { name: 'Argentina', iso: 'AR', countryCode: 54, priority: 0 },
  { name: 'Armenia', iso: 'AM', countryCode: 374, priority: 0 },
  { name: 'Aruba', iso: 'AW', countryCode: 297, priority: 0 },
  { name: 'Australia', iso: 'AU', countryCode: 61, priority: 0 },
  { name: 'Austria', iso: 'AT', countryCode: 43, priority: 0 },
  { name: 'Azerbaijan', iso: 'AZ', countryCode: 994, priority: 0 },
  { name: 'Bahamas', iso: 'BS', countryCode: 1, priority: 8 },
  { name: 'Bahrain', iso: 'BH', countryCode: 973, priority: 0 },
  { name: 'Bangladesh', iso: 'BD', countryCode: 880, priority: 0 },
  { name: 'Barbados', iso: 'BB', countryCode: 1, priority: 9 },
  { name: 'Belarus', iso: 'BY', countryCode: 375, priority: 0 },
  { name: 'Belgium', iso: 'BE', countryCode: 32, priority: 0 },
  { name: 'Belize', iso: 'BZ', countryCode: 501, priority: 0 },
  { name: 'Benin', iso: 'BJ', countryCode: 229, priority: 0 },
  { name: 'Bermuda', iso: 'BM', countryCode: 1, priority: 0 },
  { name: 'Bhutan', iso: 'BT', countryCode: 975, priority: 0 },
  { name: 'Bolivia', iso: 'BO', countryCode: 591, priority: 0 },
  { name: 'Bosnia and Herzegovina', iso: 'BA', countryCode: 387, priority: 0 },
  { name: 'Botswana', iso: 'BW', countryCode: 267, priority: 0 },
  { name: 'Brazil', iso: 'BR', countryCode: 55, priority: 0 },
  {
    name: 'British Indian Ocean Territory',
    iso: 'IO',
    countryCode: 246,
    priority: 0,
  },
  { name: 'British Virgin Islands', iso: 'VG', countryCode: 1, priority: 0 },
  { name: 'Brunei', iso: 'BN', countryCode: 673, priority: 0 },
  { name: 'Bulgaria', iso: 'BG', countryCode: 359, priority: 0 },
  { name: 'Burkina Faso', iso: 'BF', countryCode: 226, priority: 0 },
  { name: 'Burundi', iso: 'BI', countryCode: 257, priority: 0 },
  { name: 'Cambodia', iso: 'KH', countryCode: 855, priority: 0 },
  { name: 'Cameroon', iso: 'CM', countryCode: 237, priority: 0 },
  { name: 'Canada', iso: 'CA', countryCode: 1, priority: 1 },
  { name: 'Cape Verde', iso: 'CV', countryCode: 238, priority: 0 },
  { name: 'Cayman Islands', iso: 'KY', countryCode: 1, priority: 0 },
  {
    name: 'Central African Republic',
    iso: 'CF',
    countryCode: 236,
    priority: 0,
  },
  { name: 'Chad', iso: 'TD', countryCode: 235, priority: 0 },
  { name: 'Chile', iso: 'CL', countryCode: 56, priority: 0 },
  { name: 'China', iso: 'CN', countryCode: 86, priority: 0 },
  { name: 'Christmas Island', iso: 'CX', countryCode: 61, priority: 0 },
  { name: 'Cocos (Keeling) Islands', iso: 'CC', countryCode: 61, priority: 0 },
  { name: 'Colombia', iso: 'CO', countryCode: 57, priority: 0 },
  { name: 'Comoros', iso: 'KM', countryCode: 269, priority: 0 },
  { name: 'Congo (Brazzaville)', iso: 'CG', countryCode: 242, priority: 0 },
  { name: 'Congo (Kinshasa)', iso: 'CD', countryCode: 243, priority: 0 },
  { name: 'Cook Islands', iso: 'CK', countryCode: 682, priority: 0 },
  { name: 'Costa Rica', iso: 'CR', countryCode: 506, priority: 0 },
  { name: 'Côte d’Ivoire', iso: 'CI', countryCode: 225, priority: 0 },
  { name: 'Croatia', iso: 'HR', countryCode: 385, priority: 0 },
  { name: 'Cuba', iso: 'CU', countryCode: 53, priority: 0 },
  { name: 'Curaçao', iso: 'CW', countryCode: 599, priority: 0 },
  { name: 'Cyprus', iso: 'CY', countryCode: 357, priority: 0 },
  { name: 'Czech Republic', iso: 'CZ', countryCode: 420, priority: 0 },
  { name: 'Denmark', iso: 'DK', countryCode: 45, priority: 0 },
  { name: 'Djibouti', iso: 'DJ', countryCode: 253, priority: 0 },
  { name: 'Dominica', iso: 'DM', countryCode: 1, priority: 13 },
  { name: 'Dominican Republic', iso: 'DO', countryCode: 1, priority: 0 },
  { name: 'Ecuador', iso: 'EC', countryCode: 593, priority: 0 },
  { name: 'Egypt', iso: 'EG', countryCode: 20, priority: 0 },
  { name: 'El Salvador', iso: 'SV', countryCode: 503, priority: 0 },
  { name: 'Equatorial Guinea', iso: 'GQ', countryCode: 240, priority: 0 },
  { name: 'Eritrea', iso: 'ER', countryCode: 291, priority: 0 },
  { name: 'Estonia', iso: 'EE', countryCode: 372, priority: 0 },
  { name: 'Eswatini', iso: 'SZ', countryCode: 268, priority: 0 },
  { name: 'Ethiopia', iso: 'ET', countryCode: 251, priority: 0 },
  { name: 'Falkland Islands', iso: 'FK', countryCode: 500, priority: 0 },
  { name: 'Faroe Islands', iso: 'FO', countryCode: 298, priority: 0 },
  { name: 'Fiji', iso: 'FJ', countryCode: 679, priority: 0 },
  { name: 'Finland', iso: 'FI', countryCode: 358, priority: 0 },
  { name: 'France', iso: 'FR', countryCode: 33, priority: 0 },
  { name: 'French Guiana', iso: 'GF', countryCode: 594, priority: 0 },
  { name: 'French Polynesia', iso: 'PF', countryCode: 689, priority: 0 },
  { name: 'Gabon', iso: 'GA', countryCode: 241, priority: 0 },
  { name: 'Gambia', iso: 'GM', countryCode: 220, priority: 0 },
  { name: 'Georgia', iso: 'GE', countryCode: 995, priority: 0 },
  { name: 'Germany', iso: 'DE', countryCode: 49, priority: 0 },
  { name: 'Ghana', iso: 'GH', countryCode: 233, priority: 0 },
  { name: 'Gibraltar', iso: 'GI', countryCode: 350, priority: 0 },
  { name: 'Greece', iso: 'GR', countryCode: 30, priority: 0 },
  { name: 'Greenland', iso: 'GL', countryCode: 299, priority: 0 },
  { name: 'Grenada', iso: 'GD', countryCode: 1, priority: 14 },
  { name: 'Guadeloupe', iso: 'GP', countryCode: 590, priority: 0 },
  { name: 'Guam', iso: 'GU', countryCode: 1, priority: 15 },
  { name: 'Guatemala', iso: 'GT', countryCode: 502, priority: 0 },
  { name: 'Guernsey', iso: 'GG', countryCode: 44, priority: 1 },
  { name: 'Guinea', iso: 'GN', countryCode: 224, priority: 0 },
  { name: 'Guinea-Bissau', iso: 'GW', countryCode: 245, priority: 0 },
  { name: 'Guyana', iso: 'GY', countryCode: 592, priority: 0 },
  { name: 'Haiti', iso: 'HT', countryCode: 509, priority: 0 },
  { name: 'Honduras', iso: 'HN', countryCode: 504, priority: 0 },
  { name: 'Hong Kong', iso: 'HK', countryCode: 852, priority: 0 },
  { name: 'Hungary', iso: 'HU', countryCode: 36, priority: 0 },
  { name: 'Iceland', iso: 'IS', countryCode: 354, priority: 0 },
  { name: 'India', iso: 'IN', countryCode: 91, priority: 0 },
  { name: 'Indonesia', iso: 'ID', countryCode: 62, priority: 0 },
  { name: 'Iran', iso: 'IR', countryCode: 98, priority: 0 },
  { name: 'Iraq', iso: 'IQ', countryCode: 964, priority: 0 },
  { name: 'Ireland', iso: 'IE', countryCode: 353, priority: 0 },
  { name: 'Isle of Man', iso: 'IM', countryCode: 44, priority: 0 },
  { name: 'Israel', iso: 'IL', countryCode: 972, priority: 0 },
  { name: 'Italy', iso: 'IT', countryCode: 39, priority: 0 },
  { name: 'Jamaica', iso: 'JM', countryCode: 1, priority: 0 },
  { name: 'Japan', iso: 'JP', countryCode: 81, priority: 0 },
  { name: 'Jersey', iso: 'JE', countryCode: 44, priority: 0 },
  { name: 'Jordan', iso: 'JO', countryCode: 962, priority: 0 },
  { name: 'Kazakhstan', iso: 'KZ', countryCode: 7, priority: 0 },
  { name: 'Kenya', iso: 'KE', countryCode: 254, priority: 0 },
  { name: 'Kiribati', iso: 'KI', countryCode: 686, priority: 0 },
  { name: 'Kosovo', iso: 'XK', countryCode: 383, priority: 0 },
  { name: 'Kuwait', iso: 'KW', countryCode: 965, priority: 0 },
  { name: 'Kyrgyzstan', iso: 'KG', countryCode: 996, priority: 0 },
  { name: 'Laos', iso: 'LA', countryCode: 856, priority: 0 },
  { name: 'Latvia', iso: 'LV', countryCode: 371, priority: 0 },
  { name: 'Lebanon', iso: 'LB', countryCode: 961, priority: 0 },
  { name: 'Lesotho', iso: 'LS', countryCode: 266, priority: 0 },
  { name: 'Liberia', iso: 'LR', countryCode: 231, priority: 0 },
  { name: 'Libya', iso: 'LY', countryCode: 218, priority: 0 },
  { name: 'Liechtenstein', iso: 'LI', countryCode: 423, priority: 0 },
  { name: 'Lithuania', iso: 'LT', countryCode: 370, priority: 0 },
  { name: 'Luxembourg', iso: 'LU', countryCode: 352, priority: 0 },
  { name: 'Macao', iso: 'MO', countryCode: 853, priority: 0 },
  { name: 'Madagascar', iso: 'MG', countryCode: 261, priority: 0 },
  { name: 'Malawi', iso: 'MW', countryCode: 265, priority: 0 },
  { name: 'Malaysia', iso: 'MY', countryCode: 60, priority: 0 },
  { name: 'Maldives', iso: 'MV', countryCode: 960, priority: 0 },
  { name: 'Mali', iso: 'ML', countryCode: 223, priority: 0 },
  { name: 'Malta', iso: 'MT', countryCode: 356, priority: 0 },
  { name: 'Marshall Islands', iso: 'MH', countryCode: 692, priority: 0 },
  { name: 'Martinique', iso: 'MQ', countryCode: 596, priority: 0 },
  { name: 'Mauritania', iso: 'MR', countryCode: 222, priority: 0 },
  { name: 'Mauritius', iso: 'MU', countryCode: 230, priority: 0 },
  { name: 'Mayotte', iso: 'YT', countryCode: 262, priority: 0 },
  { name: 'Mexico', iso: 'MX', countryCode: 52, priority: 0 },
  { name: 'Micronesia', iso: 'FM', countryCode: 691, priority: 0 },
  { name: 'Moldova', iso: 'MD', countryCode: 373, priority: 0 },
  { name: 'Monaco', iso: 'MC', countryCode: 377, priority: 0 },
  { name: 'Mongolia', iso: 'MN', countryCode: 976, priority: 0 },
  { name: 'Montenegro', iso: 'ME', countryCode: 382, priority: 0 },
  { name: 'Montserrat', iso: 'MS', countryCode: 1, priority: 16 },
  { name: 'Morocco', iso: 'MA', countryCode: 212, priority: 0 },
  { name: 'Mozambique', iso: 'MZ', countryCode: 258, priority: 0 },
  { name: 'Myanmar', iso: 'MM', countryCode: 95, priority: 0 },
  { name: 'Namibia', iso: 'NA', countryCode: 264, priority: 0 },
  { name: 'Nauru', iso: 'NR', countryCode: 674, priority: 0 },
  { name: 'Nepal', iso: 'NP', countryCode: 977, priority: 0 },
  { name: 'Netherlands', iso: 'NL', countryCode: 31, priority: 0 },
  { name: 'New Caledonia', iso: 'NC', countryCode: 687, priority: 0 },
  { name: 'New Zealand', iso: 'NZ', countryCode: 64, priority: 0 },
  { name: 'Nicaragua', iso: 'NI', countryCode: 505, priority: 0 },
  { name: 'Niger', iso: 'NE', countryCode: 227, priority: 0 },
  { name: 'Nigeria', iso: 'NG', countryCode: 234, priority: 0 },
  { name: 'Niue', iso: 'NU', countryCode: 683, priority: 0 },
  { name: 'Norfolk Island', iso: 'NF', countryCode: 672, priority: 0 },
  { name: 'North Korea', iso: 'KP', countryCode: 850, priority: 0 },
  { name: 'North Macedonia', iso: 'MK', countryCode: 389, priority: 0 },
  { name: 'Northern Mariana Islands', iso: 'MP', countryCode: 1, priority: 0 },
  { name: 'Norway', iso: 'NO', countryCode: 47, priority: 0 },
  { name: 'Oman', iso: 'OM', countryCode: 968, priority: 0 },
  { name: 'Pakistan', iso: 'PK', countryCode: 92, priority: 0 },
  { name: 'Palau', iso: 'PW', countryCode: 680, priority: 0 },
  { name: 'Palestinian Territories', iso: 'PS', countryCode: 970, priority: 0 },
  { name: 'Panama', iso: 'PA', countryCode: 507, priority: 0 },
  { name: 'Papua New Guinea', iso: 'PG', countryCode: 675, priority: 0 },
  { name: 'Paraguay', iso: 'PY', countryCode: 595, priority: 0 },
  { name: 'Peru', iso: 'PE', countryCode: 51, priority: 0 },
  { name: 'Philippines', iso: 'PH', countryCode: 63, priority: 0 },
  { name: 'Poland', iso: 'PL', countryCode: 48, priority: 0 },
  { name: 'Portugal', iso: 'PT', countryCode: 351, priority: 0 },
  { name: 'Puerto Rico', iso: 'PR', countryCode: 1, priority: 0 },
  { name: 'Qatar', iso: 'QA', countryCode: 974, priority: 0 },
  { name: 'Réunion', iso: 'RE', countryCode: 262, priority: 0 },
  { name: 'Romania', iso: 'RO', countryCode: 40, priority: 0 },
  { name: 'Russia', iso: 'RU', countryCode: 7, priority: 0 },
  { name: 'Rwanda', iso: 'RW', countryCode: 250, priority: 0 },
  { name: 'Samoa', iso: 'WS', countryCode: 685, priority: 0 },
  { name: 'San Marino', iso: 'SM', countryCode: 378, priority: 0 },
  { name: 'São Tomé and Príncipe', iso: 'ST', countryCode: 239, priority: 0 },
  { name: 'Saudi Arabia', iso: 'SA', countryCode: 966, priority: 0 },
  { name: 'Senegal', iso: 'SN', countryCode: 221, priority: 0 },
  { name: 'Serbia', iso: 'RS', countryCode: 381, priority: 0 },
  { name: 'Seychelles', iso: 'SC', countryCode: 248, priority: 0 },
  { name: 'Sierra Leone', iso: 'SL', countryCode: 232, priority: 0 },
  { name: 'Singapore', iso: 'SG', countryCode: 65, priority: 0 },
  { name: 'Sint Maarten', iso: 'SX', countryCode: 1, priority: 21 },
  { name: 'Slovakia', iso: 'SK', countryCode: 421, priority: 0 },
  { name: 'Slovenia', iso: 'SI', countryCode: 386, priority: 0 },
  { name: 'Solomon Islands', iso: 'SB', countryCode: 677, priority: 0 },
  { name: 'Somalia', iso: 'SO', countryCode: 252, priority: 0 },
  { name: 'South Africa', iso: 'ZA', countryCode: 27, priority: 0 },
  { name: 'South Korea', iso: 'KR', countryCode: 82, priority: 0 },
  { name: 'South Sudan', iso: 'SS', countryCode: 211, priority: 0 },
  { name: 'Spain', iso: 'ES', countryCode: 34, priority: 0 },
  { name: 'Sri Lanka', iso: 'LK', countryCode: 94, priority: 0 },
  { name: 'St. Barthélemy', iso: 'BL', countryCode: 590, priority: 0 },
  { name: 'St. Helena', iso: 'SH', countryCode: 290, priority: 0 },
  { name: 'St. Kitts and Nevis', iso: 'KN', countryCode: 1, priority: 0 },
  { name: 'St. Lucia', iso: 'LC', countryCode: 1, priority: 0 },
  { name: 'St. Martin', iso: 'MF', countryCode: 590, priority: 0 },
  { name: 'St. Pierre and Miquelon', iso: 'PM', countryCode: 508, priority: 0 },
  { name: 'St. Vincent and the Grenadines', iso: 'VC', countryCode: 1, priority: 0 },
  { name: 'Sudan', iso: 'SD', countryCode: 249, priority: 0 },
  { name: 'Suriname', iso: 'SR', countryCode: 597, priority: 0 },
  { name: 'Svalbard and Jan Mayen', iso: 'SJ', countryCode: 47, priority: 0 },
  { name: 'Sweden', iso: 'SE', countryCode: 46, priority: 0 },
  { name: 'Switzerland', iso: 'CH', countryCode: 41, priority: 0 },
  { name: 'Syria', iso: 'SY', countryCode: 963, priority: 0 },
  { name: 'Taiwan', iso: 'TW', countryCode: 886, priority: 0 },
  { name: 'Tajikistan', iso: 'TJ', countryCode: 992, priority: 0 },
  { name: 'Tanzania', iso: 'TZ', countryCode: 255, priority: 0 },
  { name: 'Thailand', iso: 'TH', countryCode: 66, priority: 0 },
  { name: 'Timor-Leste', iso: 'TL', countryCode: 670, priority: 0 },
  { name: 'Togo', iso: 'TG', countryCode: 228, priority: 0 },
  { name: 'Tokelau', iso: 'TK', countryCode: 690, priority: 0 },
  { name: 'Tonga', iso: 'TO', countryCode: 676, priority: 0 },
  { name: 'Trinidad and Tobago', iso: 'TT', countryCode: 1, priority: 0 },
  { name: 'Tunisia', iso: 'TN', countryCode: 216, priority: 0 },
  { name: 'Turkey', iso: 'TR', countryCode: 90, priority: 0 },
  { name: 'Turkmenistan', iso: 'TM', countryCode: 993, priority: 0 },
  { name: 'Turks and Caicos Islands', iso: 'TC', countryCode: 1, priority: 0 },
  { name: 'Tuvalu', iso: 'TV', countryCode: 688, priority: 0 },
  { name: 'Uganda', iso: 'UG', countryCode: 256, priority: 0 },
  { name: 'Ukraine', iso: 'UA', countryCode: 380, priority: 0 },
  { name: 'United Arab Emirates', iso: 'AE', countryCode: 971, priority: 0 },
  { name: 'United Kingdom', iso: 'GB', countryCode: 44, priority: 0 },
  { name: 'United States', iso: 'US', countryCode: 1, priority: 0 },
  { name: 'Uruguay', iso: 'UY', countryCode: 598, priority: 0 },
  { name: 'U.S. Virgin Islands', iso: 'VI', countryCode: 1, priority: 0 },
  { name: 'Uzbekistan', iso: 'UZ', countryCode: 998, priority: 0 },
  { name: 'Vanuatu', iso: 'VU', countryCode: 678, priority: 0 },
  { name: 'Vatican City', iso: 'VA', countryCode: 39, priority: 0 },
  { name: 'Venezuela', iso: 'VE', countryCode: 58, priority: 0 },
  { name: 'Vietnam', iso: 'VN', countryCode: 84, priority: 0 },
  { name: 'Wallis and Futuna', iso: 'WF', countryCode: 681, priority: 0 },
  { name: 'Western Sahara', iso: 'EH', countryCode: 212, priority: 0 },
  { name: 'Yemen', iso: 'YE', countryCode: 967, priority: 0 },
  { name: 'Zambia', iso: 'ZM', countryCode: 260, priority: 0 },
  { name: 'Zimbabwe', iso: 'ZW', countryCode: 263, priority: 0 },
]

export default countries
